"""add missing columns to fraud_detection

Revision ID: 1430b8e61515
Revises: 1cb0ebeb16f1
Create Date: 2026-05-22 22:41:54.180249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1430b8e61515'
down_revision: Union[str, Sequence[str], None] = '1cb0ebeb16f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fraud_detection', sa.Column('unknown_device', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='business')
    op.add_column('fraud_detection', sa.Column('face_mismatch_detected', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='business')
    op.add_column('fraud_detection', sa.Column('liveness_failed', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='business')
    op.add_column('fraud_detection', sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True), schema='business')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fraud_detection', 'confidence_score', schema='business')
    op.drop_column('fraud_detection', 'liveness_failed', schema='business')
    op.drop_column('fraud_detection', 'face_mismatch_detected', schema='business')
    op.drop_column('fraud_detection', 'unknown_device', schema='business')
    # ### end Alembic commands ###
