"""add face_reference table

Revision ID: 1cb0ebeb16f1
Revises: 495dabd80749
Create Date: 2026-05-22 00:01:42.039883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb0ebeb16f1'
down_revision: Union[str, Sequence[str], None] = '495dabd80749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_reference',
    sa.Column('face_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('face_object_key', sa.String(length=500), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['business.employee.employee_id'], name='fk_business_face_reference_employee_id_employee', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('face_id'),
    sa.UniqueConstraint('employee_id'),
    schema='business'
    )
    op.create_index('ix_business_face_reference_employee_id', 'face_reference', ['employee_id'], unique=True, schema='business')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_business_face_reference_employee_id', table_name='face_reference', schema='business')
    op.drop_table('face_reference', schema='business')
    # ### end Alembic commands ###
