"""update device model for multi-device support

Revision ID: 495dabd80749
Revises: ded99b0669c2
Create Date: 2026-05-20 22:26:16.637237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '495dabd80749'
down_revision: Union[str, Sequence[str], None] = 'ded99b0669c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('ip_address', sa.String(length=45), nullable=True), schema='business')
    op.add_column('device', sa.Column('os_version', sa.String(length=100), nullable=True), schema='business')
    op.add_column('device', sa.Column('app_version', sa.String(length=50), nullable=True), schema='business')
    op.add_column('device', sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False), schema='business')
    op.drop_index(op.f('ix_business_device_device_fingerprint'), table_name='device', schema='business')
    op.create_index('ix_business_device_device_fingerprint', 'device', ['device_fingerprint'], unique=False, schema='business')
    op.drop_index(op.f('ix_business_device_employee_id'), table_name='device', schema='business')
    op.create_index('ix_business_device_employee_id', 'device', ['employee_id'], unique=False, schema='business')
    op.create_unique_constraint('uq_business_device_employee_fingerprint', 'device', ['employee_id', 'device_fingerprint'], schema='business')
    op.drop_column('device', 'register_at', schema='business')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('register_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False), schema='business')
    op.drop_constraint('uq_business_device_employee_fingerprint', 'device', schema='business', type_='unique')
    op.drop_index('ix_business_device_employee_id', table_name='device', schema='business')
    op.create_index(op.f('ix_business_device_employee_id'), 'device', ['employee_id'], unique=True, schema='business')
    op.drop_index('ix_business_device_device_fingerprint', table_name='device', schema='business')
    op.create_index(op.f('ix_business_device_device_fingerprint'), 'device', ['device_fingerprint'], unique=True, schema='business')
    op.drop_column('device', 'registered_at', schema='business')
    op.drop_column('device', 'app_version', schema='business')
    op.drop_column('device', 'os_version', schema='business')
    op.drop_column('audit_log', 'ip_address', schema='business')
    # ### end Alembic commands ###
