"""create business and gis schemas

Revision ID: 5072b8ca88f8
Revises: 
Create Date: 2026-05-20 10:14:23.512808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5072b8ca88f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS business'))
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS gis'))

    op.create_table('department',
    sa.Column('department_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('department_id'),
    schema='business'
    )
    op.create_index('ix_business_department_manager_id', 'department', ['manager_id'], unique=False, schema='business')
    op.create_index('ix_business_department_name', 'department', ['name'], unique=True, schema='business')
    op.create_table('building',
    sa.Column('building_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('center_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('center_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('arcgis_layer_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('building_id'),
    schema='gis'
    )
    op.create_table('employee',
    sa.Column('employee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'on_leave', 'terminated', name='employee_status', schema='business'), server_default='active', nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['business.department.department_id'], name='fk_business_employee_department_id_department', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('employee_id'),
    schema='business'
    )
    op.create_index('ix_business_employee_department_id', 'employee', ['department_id'], unique=False, schema='business')
    op.create_index('ix_business_employee_email', 'employee', ['email'], unique=True, schema='business')
    op.create_index('ix_business_employee_phone', 'employee', ['phone'], unique=True, schema='business')
    op.create_index('ix_business_employee_status', 'employee', ['status'], unique=False, schema='business')
    op.create_foreign_key('fk_business_department_manager_id_employee', 'department', 'employee', ['manager_id'], ['employee_id'], source_schema='business', referent_schema='business', ondelete='SET NULL')
    op.create_table('floor',
    sa.Column('floor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('floor_name', sa.String(length=100), nullable=True),
    sa.Column('altitude_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('altitude_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['gis.building.building_id'], name='fk_gis_floor_building_id_building'),
    sa.PrimaryKeyConstraint('floor_id'),
    schema='gis'
    )
    op.create_table('account',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('employee', 'hr', 'manager', 'admin', name='account_role', schema='business'), server_default='employee', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['business.employee.employee_id'], name='fk_business_account_employee_id_employee', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id'),
    schema='business'
    )
    op.create_index('ix_business_account_employee_id', 'account', ['employee_id'], unique=True, schema='business')
    op.create_index('ix_business_account_is_active', 'account', ['is_active'], unique=False, schema='business')
    op.create_index('ix_business_account_role', 'account', ['role'], unique=False, schema='business')
    op.create_index('ix_business_account_username', 'account', ['username'], unique=True, schema='business')
    op.create_table('device',
    sa.Column('device_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.Enum('android', 'ios', 'web', 'other', name='device_platform', schema='business'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('register_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['business.employee.employee_id'], name='fk_business_device_employee_id_employee', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id'),
    schema='business'
    )
    op.create_index('ix_business_device_device_fingerprint', 'device', ['device_fingerprint'], unique=True, schema='business')
    op.create_index('ix_business_device_employee_id', 'device', ['employee_id'], unique=True, schema='business')
    op.create_index('ix_business_device_is_trusted', 'device', ['is_trusted'], unique=False, schema='business')
    op.create_index('ix_business_device_platform', 'device', ['platform'], unique=False, schema='business')
    op.create_table('shift',
    sa.Column('shift_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('late_tolerance_min', sa.Integer(), server_default='0', nullable=False),
    sa.Column('early_leave_min', sa.Integer(), server_default='0', nullable=False),
    sa.Column('apply_to_weekends', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('early_leave_min >= 0', name='ck_business_shift_early_leave_min_non_negative'),
    sa.CheckConstraint('late_tolerance_min >= 0', name='ck_business_shift_late_tolerance_min_non_negative'),
    sa.ForeignKeyConstraint(['employee_id'], ['business.employee.employee_id'], name='fk_business_shift_employee_id_employee', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shift_id'),
    schema='business'
    )
    op.create_index('ix_business_shift_employee_id', 'shift', ['employee_id'], unique=False, schema='business')
    op.create_index('ix_business_shift_name', 'shift', ['name'], unique=False, schema='business')
    op.create_index('ix_business_shift_start_time_end_time', 'shift', ['start_time', 'end_time'], unique=False, schema='business')
    op.create_table('cell_space',
    sa.Column('cell_space_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('center_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('center_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('arcgis_layer_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['gis.building.building_id'], name='fk_gis_cell_space_building_id_building'),
    sa.ForeignKeyConstraint(['floor_id'], ['gis.floor.floor_id'], name='fk_gis_cell_space_floor_id_floor'),
    sa.PrimaryKeyConstraint('cell_space_id'),
    schema='gis'
    )
    op.create_table('audit_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('login', 'logout', 'create', 'update', 'delete', 'checkin', 'checkout', 'approve', 'reject', name='audit_action_type', schema='business'), nullable=False),
    sa.Column('target_entity', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['business.account.account_id'], name='fk_business_audit_log_account_id_account', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('log_id'),
    schema='business'
    )
    op.create_index('ix_business_audit_log_account_id', 'audit_log', ['account_id'], unique=False, schema='business')
    op.create_index('ix_business_audit_log_action_type', 'audit_log', ['action_type'], unique=False, schema='business')
    op.create_index('ix_business_audit_log_created_at', 'audit_log', ['created_at'], unique=False, schema='business')
    op.create_index('ix_business_audit_log_target_entity', 'audit_log', ['target_entity'], unique=False, schema='business')
    op.create_index('ix_business_audit_log_target_id', 'audit_log', ['target_id'], unique=False, schema='business')
    op.create_table('cell_space_boundary',
    sa.Column('boundary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cell_space_id', sa.Integer(), nullable=False),
    sa.Column('boundary_type', sa.String(length=100), nullable=True),
    sa.Column('boundary_geometry_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cell_space_id'], ['gis.cell_space.cell_space_id'], name='fk_gis_cell_space_boundary_cell_space_id_cell_space'),
    sa.PrimaryKeyConstraint('boundary_id'),
    schema='gis'
    )
    op.create_table('geofence_rule',
    sa.Column('geofence_rule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cell_space_id', sa.Integer(), nullable=False),
    sa.Column('allowed_radius_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('altitude_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('altitude_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('allow_checkin', sa.Boolean(), nullable=True),
    sa.Column('allow_checkout', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cell_space_id'], ['gis.cell_space.cell_space_id'], name='fk_gis_geofence_rule_cell_space_id_cell_space'),
    sa.PrimaryKeyConstraint('geofence_rule_id'),
    schema='gis'
    )
    op.create_table('gis_layer',
    sa.Column('layer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cell_space_id', sa.Integer(), nullable=False),
    sa.Column('arcgis_layer_id', sa.String(length=100), nullable=True),
    sa.Column('layer_type', sa.String(length=100), nullable=True),
    sa.Column('layer_url', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cell_space_id'], ['gis.cell_space.cell_space_id'], name='fk_gis_gis_layer_cell_space_id_cell_space'),
    sa.PrimaryKeyConstraint('layer_id'),
    schema='gis'
    )
    op.create_table('state',
    sa.Column('state_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cell_space_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('altitude', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('state_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cell_space_id'], ['gis.cell_space.cell_space_id'], name='fk_gis_state_cell_space_id_cell_space'),
    sa.PrimaryKeyConstraint('state_id'),
    schema='gis'
    )
    op.create_table('attendance_record',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('geofence_rule_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('checkin', 'checkout', name='attendance_type', schema='business'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('altitude', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('gps_accuracy', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'flagged', name='attendance_status', schema='business'), server_default='pending', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('is_late', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_early_leave', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('gps_accuracy IS NULL OR gps_accuracy >= 0', name='ck_business_attendance_record_gps_accuracy_non_negative'),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='ck_business_attendance_record_latitude_range'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='ck_business_attendance_record_longitude_range'),
    sa.ForeignKeyConstraint(['device_id'], ['business.device.device_id'], name='fk_business_attendance_record_device_id_device', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['business.employee.employee_id'], name='fk_business_attendance_record_employee_id_employee', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geofence_rule_id'], ['gis.geofence_rule.geofence_rule_id'], name='fk_business_attendance_record_geofence_rule_id_geofence_rule', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['business.shift.shift_id'], name='fk_business_attendance_record_shift_id_shift', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('record_id'),
    schema='business'
    )
    op.create_index('ix_business_attendance_record_device_id', 'attendance_record', ['device_id'], unique=False, schema='business')
    op.create_index('ix_business_attendance_record_employee_id', 'attendance_record', ['employee_id'], unique=False, schema='business')
    op.create_index('ix_business_attendance_record_geofence_rule_id', 'attendance_record', ['geofence_rule_id'], unique=False, schema='business')
    op.create_index('ix_business_attendance_record_shift_id', 'attendance_record', ['shift_id'], unique=False, schema='business')
    op.create_index('ix_business_attendance_record_status', 'attendance_record', ['status'], unique=False, schema='business')
    op.create_index('ix_business_attendance_record_timestamp', 'attendance_record', ['timestamp'], unique=False, schema='business')
    op.create_index('ix_business_attendance_record_type', 'attendance_record', ['type'], unique=False, schema='business')
    op.create_table('transition',
    sa.Column('transition_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_state_id', sa.Integer(), nullable=False),
    sa.Column('to_state_id', sa.Integer(), nullable=False),
    sa.Column('transition_type', sa.String(length=100), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['from_state_id'], ['gis.state.state_id'], name='fk_gis_transition_from_state_id_state'),
    sa.ForeignKeyConstraint(['to_state_id'], ['gis.state.state_id'], name='fk_gis_transition_to_state_id_state'),
    sa.PrimaryKeyConstraint('transition_id'),
    schema='gis'
    )
    op.create_table('fraud_detection',
    sa.Column('fraud_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('mock_location_detected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('gps_spoofing_detected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('buddy_punch_suspected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['business.attendance_record.record_id'], name='fk_business_fraud_detection_record_id_attendance_record', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fraud_id'),
    schema='business'
    )
    op.create_index('ix_business_fraud_detection_buddy_punch_suspected', 'fraud_detection', ['buddy_punch_suspected'], unique=False, schema='business')
    op.create_index('ix_business_fraud_detection_checked_at', 'fraud_detection', ['checked_at'], unique=False, schema='business')
    op.create_index('ix_business_fraud_detection_gps_spoofing_detected', 'fraud_detection', ['gps_spoofing_detected'], unique=False, schema='business')
    op.create_index('ix_business_fraud_detection_mock_location_detected', 'fraud_detection', ['mock_location_detected'], unique=False, schema='business')
    op.create_index('ix_business_fraud_detection_record_id', 'fraud_detection', ['record_id'], unique=True, schema='business')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_business_fraud_detection_record_id', table_name='fraud_detection', schema='business')
    op.drop_index('ix_business_fraud_detection_mock_location_detected', table_name='fraud_detection', schema='business')
    op.drop_index('ix_business_fraud_detection_gps_spoofing_detected', table_name='fraud_detection', schema='business')
    op.drop_index('ix_business_fraud_detection_checked_at', table_name='fraud_detection', schema='business')
    op.drop_index('ix_business_fraud_detection_buddy_punch_suspected', table_name='fraud_detection', schema='business')
    op.drop_table('fraud_detection', schema='business')
    op.drop_table('transition', schema='gis')
    op.drop_index('ix_business_attendance_record_type', table_name='attendance_record', schema='business')
    op.drop_index('ix_business_attendance_record_timestamp', table_name='attendance_record', schema='business')
    op.drop_index('ix_business_attendance_record_status', table_name='attendance_record', schema='business')
    op.drop_index('ix_business_attendance_record_shift_id', table_name='attendance_record', schema='business')
    op.drop_index('ix_business_attendance_record_geofence_rule_id', table_name='attendance_record', schema='business')
    op.drop_index('ix_business_attendance_record_employee_id', table_name='attendance_record', schema='business')
    op.drop_index('ix_business_attendance_record_device_id', table_name='attendance_record', schema='business')
    op.drop_table('attendance_record', schema='business')
    op.drop_table('state', schema='gis')
    op.drop_table('gis_layer', schema='gis')
    op.drop_table('geofence_rule', schema='gis')
    op.drop_table('cell_space_boundary', schema='gis')
    op.drop_index('ix_business_audit_log_target_id', table_name='audit_log', schema='business')
    op.drop_index('ix_business_audit_log_target_entity', table_name='audit_log', schema='business')
    op.drop_index('ix_business_audit_log_created_at', table_name='audit_log', schema='business')
    op.drop_index('ix_business_audit_log_action_type', table_name='audit_log', schema='business')
    op.drop_index('ix_business_audit_log_account_id', table_name='audit_log', schema='business')
    op.drop_table('audit_log', schema='business')
    op.drop_table('cell_space', schema='gis')
    op.drop_index('ix_business_shift_start_time_end_time', table_name='shift', schema='business')
    op.drop_index('ix_business_shift_name', table_name='shift', schema='business')
    op.drop_index('ix_business_shift_employee_id', table_name='shift', schema='business')
    op.drop_table('shift', schema='business')
    op.drop_index('ix_business_device_platform', table_name='device', schema='business')
    op.drop_index('ix_business_device_is_trusted', table_name='device', schema='business')
    op.drop_index('ix_business_device_employee_id', table_name='device', schema='business')
    op.drop_index('ix_business_device_device_fingerprint', table_name='device', schema='business')
    op.drop_table('device', schema='business')
    op.drop_index('ix_business_account_username', table_name='account', schema='business')
    op.drop_index('ix_business_account_role', table_name='account', schema='business')
    op.drop_index('ix_business_account_is_active', table_name='account', schema='business')
    op.drop_index('ix_business_account_employee_id', table_name='account', schema='business')
    op.drop_table('account', schema='business')
    op.drop_table('floor', schema='gis')
    op.drop_index('ix_business_employee_status', table_name='employee', schema='business')
    op.drop_index('ix_business_employee_phone', table_name='employee', schema='business')
    op.drop_index('ix_business_employee_email', table_name='employee', schema='business')
    op.drop_index('ix_business_employee_department_id', table_name='employee', schema='business')
    op.drop_constraint('fk_business_department_manager_id_employee', 'department', schema='business', type_='foreignkey')
    op.drop_table('employee', schema='business')
    op.drop_table('building', schema='gis')
    op.drop_index('ix_business_department_name', table_name='department', schema='business')
    op.drop_index('ix_business_department_manager_id', table_name='department', schema='business')
    op.drop_table('department', schema='business')
    op.execute(sa.text('DROP TYPE IF EXISTS business.audit_action_type'))
    op.execute(sa.text('DROP TYPE IF EXISTS business.attendance_status'))
    op.execute(sa.text('DROP TYPE IF EXISTS business.attendance_type'))
    op.execute(sa.text('DROP TYPE IF EXISTS business.device_platform'))
    op.execute(sa.text('DROP TYPE IF EXISTS business.account_role'))
    op.execute(sa.text('DROP TYPE IF EXISTS business.employee_status'))
    op.execute(sa.text('DROP SCHEMA IF EXISTS gis'))
    op.execute(sa.text('DROP SCHEMA IF EXISTS business'))
    # ### end Alembic commands ###
