"""add notification and notification_preference tables

Revision ID: 6b9d84669f48
Revises: 1430b8e61515
Create Date: 2026-05-22 23:17:16.008487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9d84669f48'
down_revision: Union[str, Sequence[str], None] = '1430b8e61515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('checkin_approved', 'checkin_rejected', 'checkout_approved', 'checkout_rejected', 'device_trusted', 'exception_flagged', name='notification_type', schema='business'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['business.account.account_id'], name='fk_business_notification_account_id_account', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id'),
    schema='business'
    )
    op.create_index('ix_business_notification_account_id', 'notification', ['account_id'], unique=False, schema='business')
    op.create_index('ix_business_notification_created_at', 'notification', ['created_at'], unique=False, schema='business')
    op.create_index('ix_business_notification_is_read', 'notification', ['is_read'], unique=False, schema='business')
    op.create_index('ix_business_notification_type', 'notification', ['type'], unique=False, schema='business')
    op.create_table('notification_preference',
    sa.Column('preference_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notify_checkin_approved', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notify_checkin_rejected', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notify_checkout_approved', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notify_checkout_rejected', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notify_device_trusted', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notify_exception_flagged', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['business.account.account_id'], name='fk_business_notification_preference_account_id_account', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('preference_id'),
    sa.UniqueConstraint('account_id'),
    schema='business'
    )
    op.create_index('ix_business_notification_preference_account_id', 'notification_preference', ['account_id'], unique=True, schema='business')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_business_notification_preference_account_id', table_name='notification_preference', schema='business')
    op.drop_table('notification_preference', schema='business')
    op.drop_index('ix_business_notification_type', table_name='notification', schema='business')
    op.drop_index('ix_business_notification_is_read', table_name='notification', schema='business')
    op.drop_index('ix_business_notification_created_at', table_name='notification', schema='business')
    op.drop_index('ix_business_notification_account_id', table_name='notification', schema='business')
    op.drop_table('notification', schema='business')
    # ### end Alembic commands ###
