"""extend_attendance_record_add_new_columns

Revision ID: e8509aa02ee1
Revises: 6b9d84669f48
Create Date: 2026-05-22 23:49:29.512021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8509aa02ee1'
down_revision: Union[str, Sequence[str], None] = '6b9d84669f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_record', sa.Column('face_image_object_key', sa.String(length=500), nullable=True), schema='business')
    op.add_column('attendance_record', sa.Column('matched_checkin_record_id', sa.Integer(), nullable=True), schema='business')
    op.add_column('attendance_record', sa.Column('worked_minutes', sa.Integer(), nullable=True), schema='business')
    op.add_column('attendance_record', sa.Column('approved_by_account_id', sa.Integer(), nullable=True), schema='business')
    op.add_column('attendance_record', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True), schema='business')
    op.alter_column('attendance_record', 'geofence_rule_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='business')
    op.create_index('ix_business_attendance_record_approved_by_account_id', 'attendance_record', ['approved_by_account_id'], unique=False, schema='business')
    op.create_index('ix_business_attendance_record_matched_checkin_record_id', 'attendance_record', ['matched_checkin_record_id'], unique=False, schema='business')
    op.drop_constraint(op.f('fk_business_attendance_record_geofence_rule_id_geofence_rule'), 'attendance_record', schema='business', type_='foreignkey')
    op.create_foreign_key('fk_business_attendance_record_geofence_rule_id_geofence_rule', 'attendance_record', 'geofence_rule', ['geofence_rule_id'], ['geofence_rule_id'], source_schema='business', referent_schema='gis', ondelete='SET NULL')
    op.create_foreign_key('fk_business_attendance_record_matched_checkin_record_id', 'attendance_record', 'attendance_record', ['matched_checkin_record_id'], ['record_id'], source_schema='business', referent_schema='business', ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_business_attendance_record_approved_by_account_id', 'attendance_record', 'account', ['approved_by_account_id'], ['account_id'], source_schema='business', referent_schema='business', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_business_attendance_record_approved_by_account_id', 'attendance_record', schema='business', type_='foreignkey')
    op.drop_constraint('fk_business_attendance_record_matched_checkin_record_id', 'attendance_record', schema='business', type_='foreignkey')
    op.drop_constraint('fk_business_attendance_record_geofence_rule_id_geofence_rule', 'attendance_record', schema='business', type_='foreignkey')
    op.create_foreign_key(op.f('fk_business_attendance_record_geofence_rule_id_geofence_rule'), 'attendance_record', 'geofence_rule', ['geofence_rule_id'], ['geofence_rule_id'], source_schema='business', referent_schema='gis', ondelete='RESTRICT')
    op.drop_index('ix_business_attendance_record_matched_checkin_record_id', table_name='attendance_record', schema='business')
    op.drop_index('ix_business_attendance_record_approved_by_account_id', table_name='attendance_record', schema='business')
    op.alter_column('attendance_record', 'geofence_rule_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='business')
    op.drop_column('attendance_record', 'approved_at', schema='business')
    op.drop_column('attendance_record', 'approved_by_account_id', schema='business')
    op.drop_column('attendance_record', 'worked_minutes', schema='business')
    op.drop_column('attendance_record', 'matched_checkin_record_id', schema='business')
    op.drop_column('attendance_record', 'face_image_object_key', schema='business')
    # ### end Alembic commands ###
